port: 80
host: 0.0.0.0
livereload: true

exclude:
  - ".gitignore"
  - "README.md"
  - "Gemfile.lock"
  - "Gemfile"
  - "vendor/bundle"
  - "node_modules"
  - "screenshots"
  - "pancake"

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

collections:
  roles:
    output: true
